apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-username: cG9zdGdyZXM=  # base64 encoded 'postgres'
  postgres-password: cGFzc3dvcmQ=  # base64 encoded 'password'
